# Generated by Django 5.2.10 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, verbose_name='Alamat Lengkap'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama di Rekening'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. Rekening'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Bank'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('?', 'Tidak Diketahui')], max_length=3),
        ),
        migrations.AddField(
            model_name='employee',
            name='bpjs_kesehatan',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. BPJS Kesehatan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bpjs_kesehatan_type',
            field=models.CharField(blank=True, choices=[('1', 'Kelas 1'), ('2', 'Kelas 2'), ('3', 'Kelas 3'), ('non', 'Tidak Ada')], default='non', max_length=5, verbose_name='Kelas BPJS Kesehatan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bpjs_ketenagakerjaan',
            field=models.CharField(blank=True, max_length=30, verbose_name='No. BPJS Ketenagakerjaan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Selesai Kontrak'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Mulai Kontrak'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_major',
            field=models.CharField(blank=True, max_length=150, verbose_name='Jurusan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_school',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nama Institusi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Kontak Darurat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telepon Darurat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_relation',
            field=models.CharField(blank=True, choices=[('suami', 'Suami'), ('istri', 'Istri'), ('ayah', 'Ayah'), ('ibu', 'Ibu'), ('kakak', 'Kakak'), ('adik', 'Adik'), ('anak', 'Anak'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Hubungan Darurat'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('tetap', 'Karyawan Tetap'), ('kontrak', 'Karyawan Kontrak'), ('magang', 'Magang / Intern'), ('paruh_waktu', 'Paruh Waktu'), ('pkwt', 'PKWT'), ('pkwtt', 'PKWTT')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Ayah'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=4, verbose_name='Tahun Lulus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='kota',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kota/Kabupaten'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_education',
            field=models.CharField(blank=True, choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA/SMK'), ('d1', 'D1'), ('d2', 'D2'), ('d3', 'D3'), ('d4', 'D4'), ('s1', 'S1'), ('s2', 'S2'), ('s3', 'S3')], max_length=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('belum_kawin', 'Belum Kawin'), ('kawin', 'Kawin'), ('cerai_hidup', 'Cerai Hidup'), ('cerai_mati', 'Cerai Mati')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nama Ibu'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='WNI', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nama Panggilan'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nik',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIK / KTP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='npwp',
            field=models.CharField(blank=True, max_length=30, verbose_name='NPWP'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('kristen', 'Kristen Protestan'), ('katolik', 'Katolik'), ('hindu', 'Hindu'), ('buddha', 'Buddha'), ('konghucu', 'Konghucu'), ('lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='rt_rw',
            field=models.CharField(blank=True, max_length=10, verbose_name='RT/RW'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Masuk'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='npp',
            field=models.CharField(max_length=20, unique=True, verbose_name='NPP'),
        ),
    ]
