# Generated by Django 5.2.10 on 2026-01-26 13:54

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Nonaktifkan jika jabatan sudah tidak digunakan'),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director')], help_text='Level jabatan untuk menentukan hak & approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Nama jabatan, contoh: Staff HR, IT Support', max_length=100),
        ),
    ]
