# Generated by Django 5.2.10 on 2026-01-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_alter_position_options_position_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='level',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('manager', 'Manager'), ('director', 'Director')], max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
