# Generated by Django 5.2.10 on 2026-03-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_remove_position_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['level', 'name']},
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
