# Generated by Django 5.2.10 on 2026-03-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0004_alter_position_options_remove_position_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
    ]
