# Generated by Django 5.2.10 on 2026-01-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='npp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
