# Generated by Django 5.2.10 on 2026-03-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['company__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
    ]
