# Generated by Django 4.2.5 on 2026-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='default_days',
            field=models.IntegerField(blank=True, help_text='Jatah hari tetap (kosongkan jika fleksibel)', null=True),
        ),
    ]
