# Generated by Django 5.2.10 on 2026-03-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='company',
            name='code',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
