# Generated by Django 4.2.5 on 2026-04-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_alter_employee_options_employee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jam Kerja Reguler', max_length=50)),
                ('start_time', models.TimeField(default='08:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
                ('grace_period', models.IntegerField(default=15, help_text='Toleransi keterlambatan (menit)')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Hadir'), ('late', 'Terlambat'), ('absent', 'Alpa'), ('off', 'Libur')], default='present', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('lat_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_in', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lat_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng_out', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
