# Generated by Django 4.2.5 on 2026-04-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employee_options_employee_address_and_more'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lat_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lat_out',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lng_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='lng_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='excused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excused_attendances', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late_excused',
            field=models.BooleanField(default=False, help_text='Centang jika alasan telat diterima oleh atasan'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_evidence',
            field=models.ImageField(blank=True, help_text='Bukti foto/dokumen', null=True, upload_to='attendance/evidence/'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_reason',
            field=models.TextField(blank=True, help_text='Alasan terlambat', null=True),
        ),
    ]
