# Generated by Django 4.2.5 on 2026-04-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_lat_in_remove_attendance_lat_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='allowed_radius',
            field=models.IntegerField(default=100, help_text='Maksimal jarak absen dari kantor (dalam meter)'),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Garis Lintang (Latitude) Kantor Induk', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Garis Bujur (Longitude) Kantor Induk', max_digits=10, null=True),
        ),
    ]
